//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace is_takip.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblkategori
    {
        public int id { get; set; }
        public string kategori { get; set; }
        public bool durum { get; set; }
    }
}
