//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace is_takip.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblpersonel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblpersonel()
        {
            this.tblgorevler = new HashSet<tblgorevler>();
            this.tblgorevler1 = new HashSet<tblgorevler>();
        }
    
        public int id { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string mail { get; set; }
        public string görsel { get; set; }
        public string telefon { get; set; }
        public Nullable<int> departman { get; set; }
        public Nullable<bool> durum { get; set; }
        public string cv { get; set; }
        public string sifre { get; set; }
        public string departman2 { get; set; }
    
        public virtual tbldepartmanlar tbldepartmanlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblgorevler> tblgorevler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblgorevler> tblgorevler1 { get; set; }
    }
}
