//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace is_takip.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsatis
    {
        public int id { get; set; }
        public string urunAdı { get; set; }
        public double birimfiyat { get; set; }
        public double toplamfiyat { get; set; }
        public System.DateTime tarih { get; set; }
    }
}
