//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace is_takip.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblurunler
    {
        public int id { get; set; }
        public string adı { get; set; }
        public string urunkodu { get; set; }
        public int urunadet { get; set; }
        public double birimfiyat { get; set; }
        public double satisfiyat { get; set; }
        public string firma { get; set; }
        public string aciklama { get; set; }
        public string kategori { get; set; }
        public bool durum { get; set; }
    }
}
